"""store movement photos in db instead of ephemeral disk

Revision ID: bb8a6089a295
Revises: df828c0426b4
Create Date: 2026-08-17 17:33:24.568937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb8a6089a295'
down_revision: Union[str, Sequence[str], None] = 'df828c0426b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movements', sa.Column('photo_data', sa.LargeBinary(), nullable=True))
    op.add_column('movements', sa.Column('photo_content_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###

    # Existing photo_filename values point to files on Render's ephemeral disk
    # (free plan has no persistent disk), which are already gone. Clear them
    # so the UI stops showing a camera icon for photos that can't be viewed.
    op.execute("UPDATE movements SET photo_filename = NULL WHERE photo_filename IS NOT NULL")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movements', 'photo_content_type')
    op.drop_column('movements', 'photo_data')
    # ### end Alembic commands ###
