"""add personnel_costs table

Revision ID: df828c0426b4
Revises: c7bdb136633d
Create Date: 2026-07-28 21:37:50.251210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df828c0426b4'
down_revision: Union[str, Sequence[str], None] = 'c7bdb136633d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personnel_costs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('total_paid', sa.Float(), nullable=False),
    sa.Column('bru1_e2n', sa.Float(), nullable=False),
    sa.Column('bru2_e2n', sa.Float(), nullable=False),
    sa.Column('ratio', sa.Float(), nullable=False),
    sa.Column('bru2_cost', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'month', name='uq_personnel_year_month')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personnel_costs')
    # ### end Alembic commands ###
